# Default values for engineer-notifier.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
notifier:
  slackToken: changeme
  handleHash: '{"@paranoid-android": "@U0E20UH2L"}'
  slackChannels: '["EXAMPLE"]'
  image:
    repository: quay.io/samsung_cnct/engineer-notifier
    tag: latest
    pullPolicy: Always
seal:
  image:
    repository: quay.io/samsung_cnct/sealbot
    tag: latest
    pullPolicy: Always
  githubToken: changeme
  slackWebhook: changeme
  slackChannel: '#team-team'
  githubMembers: "paranoid-android"
  githubLabels: "[DO NOT MERGE],Don't merge,DO NOT MERGE,wip,[WIP],[NO SEAL],[NO REVIEWBOT]"
  orgs:
    - name: THESYSTEM
      crontab: "0 16 * * *"
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

